name: Tests

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.3"

      - name: Run tests
        run: go test -json ./... > test-results.json

      - name: Publish Test Report
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Test Results
          path: test-results.json
          reporter: golang-json
